[package]
name = "largetable"
version = "0.1.0"
authors = ["Colin Merkel <colin.merkel@gmail.com>"]

[dependencies]
protobuf = { git = "https://github.com/stepancheg/rust-protobuf" }
serde = "0.9"
serde_json = "0.9"
serde_derive = "0.9"
